// packages/permdock/src/svelte/Protected.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';

  import { getStore } from './context.ts';
  import { protectedView, type ProtectedProps } from './protected.ts';

  let {
    permission,
    data,
    tenant,
    children,
    pending,
    fallback,
  }: ProtectedProps = $props();

  const store = getStore();
  let tick = $state(0);
  onDestroy(
    store.subscribe(() => {
      tick += 1;
    }),
  );
  const view = $derived.by(() => {
    const generation = tick;
    return protectedView(store, permission, data, tenant, generation);
  });
</script>

{#if view.slot === 'pending'}
  {@render pending?.()}
{:else if view.slot === 'fallback'}
  {@render fallback?.(view.decision)}
{:else}
  {@render children?.(view.decision)}
{/if}

// packages/permdock/src/react/protected.tsx
import { type ReactNode, Suspense, useMemo } from "react";

import type { ProtectedProps } from "./types.ts";

import { protectedView } from "../client/views.ts";
import { usePermission, usePermDock } from "./hooks.ts";

export function Protected(props: ProtectedProps): ReactNode {
  if (props.pending === undefined) {
    return <Guard {...props} />;
  }
  return (
    <Suspense fallback={props.pending}>
      <Guard {...props} />
    </Suspense>
  );
}

function Guard(props: ProtectedProps): ReactNode {
  const root = usePermDock();
  const local = usePermission(props.permission, props.data);
  const scoped = useMemo(
    () => (props.tenant === undefined ? undefined : root.tenant(props.tenant)),
    [root, props.tenant],
  );
  const view = protectedView(local, root, props.permission, props.data, scoped);
  switch (view.slot) {
    case "pending":
      return props.pending ?? null;
    case "fallback":
      return typeof props.fallback === "function"
        ? props.fallback(view.decision)
        : (props.fallback ?? null);
    case "default":
      return typeof props.children === "function"
        ? props.children(view.decision)
        : props.children;
    default: {
      const exhausted: never = view;
      return exhausted;
    }
  }
}
