// packages/permdock/src/solid/provider.ts
import { createComponent } from 'solid-js';

import type { PermDockProviderProps } from './types.ts';

import { compact } from '../core/compact.ts';
import { createClientStore } from '../react/store.ts';
import { PermDockContext } from './context.ts';

export function PermDockProvider(props: PermDockProviderProps): unknown {
  const store = createClientStore(
    compact({
      snapshot: props.snapshot,
      endpoint: props.endpoint,
      approvals: props.approvals,
      tenant: props.tenant,
      fetch: props.fetch,
      headers: props.headers,
      maxAge: props.maxAge,
      verifier: props.verifier,
    }),
  );
  return createComponent(PermDockContext.Provider, {
    value: store,
    get children() {
      return props.children;
    },
  });
}

// packages/permdock/src/react/provider.tsx
import { type ReactElement, useMemo } from 'react';

import type { PermDockProviderProps } from './types.ts';

import { compact } from '../core/compact.ts';
import { PermDockStoreContext } from './context.ts';
import { createClientStore } from './store.ts';

export function PermDockProvider(props: PermDockProviderProps): ReactElement {
  const store = useMemo(
    () =>
      createClientStore(
        compact({
          snapshot: props.snapshot,
          endpoint: props.endpoint,
          approvals: props.approvals,
          tenant: props.tenant,
          fetch: props.fetch,
          headers: props.headers,
          maxAge: props.maxAge,
          verifier: props.verifier,
        }),
      ),
    [
      props.snapshot,
      props.endpoint,
      props.approvals,
      props.tenant,
      props.fetch,
      props.headers,
      props.maxAge,
      props.verifier,
    ],
  );
  return (
    <PermDockStoreContext value={store}>{props.children}</PermDockStoreContext>
  );
}
