// apps/examples/svelte/src/app.svelte
<script lang="ts">
  import type { Snapshot } from 'permdock';

  import { Protected, setPermDock } from 'permdock/svelte';

  import { ownPost, permissions } from './permissions.ts';

  let { snapshot }: { snapshot: Snapshot } = $props();
  const initial = snapshot;
  setPermDock({ snapshot: initial });
</script>

<Protected permission={permissions.post.update} data={ownPost}>
  <span>edit</span>
  {#snippet fallback()}<span>locked</span>{/snippet}
</Protected>
<Protected permission={permissions.post.publish} data={ownPost}>
  <span>publish</span>
  {#snippet fallback()}<span>locked</span>{/snippet}
</Protected>

// apps/examples/expo/src/app/index.tsx
import { Protected } from "permdock/react-native";
import { Text, View } from "react-native";

import { ownPost, permissions } from "../permissions.ts";

export default function Home() {
  return (
    <View>
      <Protected
        permission={permissions.post.update}
        data={ownPost}
        fallback={<Text>locked</Text>}
      >
        <Text>edit</Text>
      </Protected>
      <Protected
        permission={permissions.post.publish}
        data={ownPost}
        fallback={<Text>locked</Text>}
      >
        <Text>publish</Text>
      </Protected>
    </View>
  );
}
