// packages/permdock/src/next/provider.tsx
import type { ReactElement, ReactNode } from 'react';

import type { Snapshot } from '../core/interfaces.ts';

import { compact } from '../core/compact.ts';
import { PermDockProvider as ClientProvider } from '../react/provider.tsx';

export function renderClientProvider(options: {
  readonly snapshot: Snapshot | string;
  readonly endpoint: string;
  readonly tenant?: string;
  readonly children: ReactNode;
}): ReactElement {
  return (
    <ClientProvider
      {...compact({
        snapshot: options.snapshot,
        endpoint: options.endpoint,
        tenant: options.tenant,
      })}
    >
      {options.children}
    </ClientProvider>
  );
}

// packages/permdock/src/solid/provider.ts
import { createComponent } from 'solid-js';

import type { PermDockProviderProps } from './types.ts';

import { compact } from '../core/compact.ts';
import { createClientStore } from '../react/store.ts';
import { PermDockContext } from './context.ts';

export function PermDockProvider(props: PermDockProviderProps): unknown {
  const store = createClientStore(
    compact({
      snapshot: props.snapshot,
      endpoint: props.endpoint,
      approvals: props.approvals,
      tenant: props.tenant,
      fetch: props.fetch,
      headers: props.headers,
      maxAge: props.maxAge,
      verifier: props.verifier,
    }),
  );
  return createComponent(PermDockContext.Provider, {
    value: store,
    get children() {
      return props.children;
    },
  });
}
