// apps/examples/react-vite/src/app.tsx
import type { Snapshot } from "permdock";

import { PermDockProvider, Protected } from "permdock/react";

import { ownPost, permissions } from "./permissions.ts";

export function App(props: { readonly snapshot: Snapshot }) {
  return (
    <PermDockProvider snapshot={props.snapshot}>
      <Protected
        permission={permissions.post.update}
        data={ownPost}
        fallback={<span>locked</span>}
      >
        <span>edit</span>
      </Protected>
      <Protected
        permission={permissions.post.publish}
        data={ownPost}
        fallback={<span>locked</span>}
      >
        <span>publish</span>
      </Protected>
    </PermDockProvider>
  );
}

// apps/examples/svelte/src/app.svelte
<script lang="ts">
  import type { Snapshot } from 'permdock';

  import { Protected, setPermDock } from 'permdock/svelte';

  import { ownPost, permissions } from './permissions.ts';

  let { snapshot }: { snapshot: Snapshot } = $props();
  const initial = snapshot;
  setPermDock({ snapshot: initial });
</script>

<Protected permission={permissions.post.update} data={ownPost}>
  <span>edit</span>
  {#snippet fallback()}<span>locked</span>{/snippet}
</Protected>
<Protected permission={permissions.post.publish} data={ownPost}>
  <span>publish</span>
  {#snippet fallback()}<span>locked</span>{/snippet}
</Protected>
